pipeline {

    parameters {
        string(name: 'environment', defaultValue: 'terraform', description: 'Workspace/environment file to use for deployment')
        booleanParam(name: 'autoApprove', defaultValue: false, description: 'Automatically run apply after generating plan?')

    }


     

   agent  any
       
    stages {
        stage('checkout') {
            steps {
                 script{
                        dir("terraform")
                        {
                            git "https://github.com/surya0249/terra-code.git"
                        }
                    }
                }
            }

        stage('Plan') {
            steps {
                sudo sh 'pwd;cd terraform/terra-code ; terraform init -input=false'
                sudo sh 'pwd;cd terraform/terra-code ; terraform workspace new ${environment}'
                sudo sh 'pwd;cd terraform/terra-code ; terraform workspace select ${environment}'
                sudo sh "pwd;cd terraform/terra-code ;terraform plan -input=false -out tfplan "
                sudo sh 'pwd;cd terraform/terra-code ;terraform show -no-color tfplan > tfplan.txt'
            }
        }
        stage('Approval') {
           when {
               not {
                   equals expected: true, actual: params.autoApprove
               }
           }

           steps {
               script {
                    def plan = readFile 'terraform/terra-code/tfplan.txt'
                    input message: "Do you want to apply the plan?",
                    parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
               }
           }
       }

        stage('Apply') {
            steps {
                sudo sh "pwd;cd terraform/terra-code ; terraform apply -input=false tfplan"
            }
        }
    }

  }
